// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZxS8pGQ9X8psHP2wv_kQsT2Csb4CEMY',
    appId: '1:1094106887470:web:c94eebed9a2e8d485ff6bf',
    messagingSenderId: '1094106887470',
    projectId: 'taskmate-depd',
    authDomain: 'taskmate-depd.firebaseapp.com',
    storageBucket: 'taskmate-depd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJ0-iBBnmDkT1vjuCopu4kQ_VqB0k3X0',
    appId: '1:1094106887470:android:4cff51d08bd17d895ff6bf',
    messagingSenderId: '1094106887470',
    projectId: 'taskmate-depd',
    storageBucket: 'taskmate-depd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHA3rToC2Q7MHEkSY_l8bvXnsdwZB41Nc',
    appId: '1:1094106887470:ios:2d07fe700d2f04cc5ff6bf',
    messagingSenderId: '1094106887470',
    projectId: 'taskmate-depd',
    storageBucket: 'taskmate-depd.firebasestorage.app',
    iosBundleId: 'com.example.taskmate',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHA3rToC2Q7MHEkSY_l8bvXnsdwZB41Nc',
    appId: '1:1094106887470:ios:2d07fe700d2f04cc5ff6bf',
    messagingSenderId: '1094106887470',
    projectId: 'taskmate-depd',
    storageBucket: 'taskmate-depd.firebasestorage.app',
    iosBundleId: 'com.example.taskmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfZxS8pGQ9X8psHP2wv_kQsT2Csb4CEMY',
    appId: '1:1094106887470:web:5c013bf2eb4ab0ee5ff6bf',
    messagingSenderId: '1094106887470',
    projectId: 'taskmate-depd',
    authDomain: 'taskmate-depd.firebaseapp.com',
    storageBucket: 'taskmate-depd.firebasestorage.app',
  );
}
